version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.16.0 # Specify the Node.js version you need
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'node_modules/**/*'